{% set version = "1.0.3" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-findpython
  version: {{ version|replace("-", "_") }}

source:
  fn: findpython_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/findpython_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/findpython/findpython_{{ version }}.tar.gz


  sha256: 5486535ae2f0a123b630d8eabf93a61b730765f55dfcc8ef4f6e56e7c49408f8

build:
  number: 0
  skip: True  # [win32]


  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('findpython')"  # [not win]
    - "\"%R%\" -e \"library('findpython')\""  # [win]



about:
  home: https://github.com/trevorld/findpython
  license: MIT
  summary: Package designed to find an acceptable python binary.
  license_family: MIT
  license_file: LICENSE



extra:
  recipe-maintainers:
    - croth1
