appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: qeGv7HyptQGCv22saEpiCFwNGAXMx1FEI9X9nNb3bcBPI84CaCWAgMEqxVrSC2D1ik6huwQO1juUC0bIXe16s+PdO0ZdTxGd7RpGP5LQOxTB+OHD3SJ481dWKegK2OlPhod/nzYElX6ZwjHh2VEvnpOgsnGwaGFmNsBwuLIlFA9YkuzuT4H9s/jwEe0QgzW9HyeX5eOvktqUNbonrRF3fYqDprP6Hw3A6FJgaY7n4j/EEunMy0UntIsMTzGQkd+ai2QlBXEYRtSzaNZDVl7ILIj2+UNbZA0xE+2BYfJkED4i6VldFYO2TYsMM69cAYmskzz72Efd2J6F1Qrdr/c34Y1xXYytcE0vSLkWjv3xRlrN0L8q8iaM55i3UVI3gwSCmn+vIhLAsBmBlMT8opU7YMYB6in5rDh1SR1zPKkn/dDsxyH9k+PYFiG1kMTnOr6mBgXgxnHflnUWdQy4YXkWnCNvbGjT0+D3Tg0JoajLgN7XvVxJAXRW6FYppOkd2hicg8MUCu/BCtfP9w8tHZMckA8+6ig3XvFekEMAq09ZEBl6mNe3Ynvd0gGy2nBGdsb8eh9LK0oCisyQEl/pvTR9KsQtK9DYVP1+6pwlhGAh+v8Wbo4Xx8q9XsGhI0zmfoenX7Bm3GBv29MpDnBhgzuf4M8VzOBdMCjGWvuC7W59PUA=
